from . import pms_folio
from . import pms_reservation
from . import pms_custom_menu
from . import pms_service
from . import pms_room_type
from . import pms_checkin_partner
from . import pms_ubication
from . import pms_property
from . import res_partner
