from . import pms_folio
from . import pms_reservation
from . import pms_custom_menu
from . import pms_service
from . import pms_room_type
from . import pms_checkin_partner
from . import pms_ubication
from . import pms_property
from . import res_partner
from . import res_users
from . import pms_user_calendar_property
from . import account_bank_statement
from . import pms_pwa_event
